services:
  environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/today_fridge
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_FASTAPI_BASE_URL: http://fastapi:8000
      APP_UPLOAD_ROOT_PATH: /app/uploads
  mailpit:
    image: axllent/mailpit
    container_name: today_fridge_mailpit
    ports:
      - "8025:8025" # Web UI port
      - "1025:1025" # SMTP port
    environment:
      MP_MAX_MESSAGES: 500 
  depends_on:
    - postgres
    - fastapi
  volumes:
    postgres_data:
