-- ===================================================================================
-- [postgre_init3.sql] 마이그레이션 패치 스크립트
-- 목적:
--   Fix 1. stock_status 컬럼 타입 ENUM → VARCHAR(255) 변경 (JPA @Enumerated 호환)
--   Fix 2. recipe_embedding 테이블 생성 (pgvector 확장 필요)
--   Check. postgre_init2.sql 인덱스 적용 여부 확인 → 이미 적용됨, 추가 작업 없음
--
-- 사전 조건:
--   - pgvector 확장이 설치된 PostgreSQL이어야 합니다 (Docker: pgvector/pgvector:pg16)
--   - postgre_init.sql 이 먼저 실행된 상태여야 합니다
-- ===================================================================================


-- ===================================================================================
-- [Fix 1] stock_status 컬럼 타입 변경: PostgreSQL ENUM → VARCHAR(255)
--
-- 원인: JPA @Enumerated(EnumType.STRING) 은 VARCHAR 컬럼을 기대하지만,
--       DB 에 today_fridge.stock_status 커스텀 ENUM 타입으로 정의되어 있어
--       Hibernate ddl-auto: update 실행 시 ALTER 충돌 오류 발생
--
-- 실행 순서가 중요합니다:
--   1. ENUM DEFAULT 제거  →  2. 부분 인덱스 제거  →  3. 타입 변경  →  4. DEFAULT/인덱스 재생성
--   순서가 틀리면 "operator does not exist: character varying = today_fridge.stock_status" 오류 발생
-- ===================================================================================

BEGIN;

-- Step 1: ENUM 타입으로 바인딩된 DEFAULT 먼저 제거
--         (DEFAULT 가 ENUM 타입으로 남아 있으면 타입 변경 시 충돌)
ALTER TABLE today_fridge.shopping_item_mcp
    ALTER COLUMN stock_status DROP DEFAULT;

-- Step 2: WHERE 절에서 ENUM 비교를 사용하는 부분 인덱스 제거
--         (인덱스가 남아 있으면 "operator does not exist" 오류 발생)
DROP INDEX IF EXISTS today_fridge.idx_sim_ingredient_price;

-- Step 3: ENUM → VARCHAR 타입 변경 (USING 으로 기존 값 명시적 캐스팅)
ALTER TABLE today_fridge.shopping_item_mcp
    ALTER COLUMN stock_status TYPE VARCHAR(255)
    USING stock_status::TEXT;

-- Step 4: VARCHAR 기반으로 DEFAULT 재설정
ALTER TABLE today_fridge.shopping_item_mcp
    ALTER COLUMN stock_status SET DEFAULT 'IN_STOCK';

-- Step 5: 부분 인덱스 재생성 (VARCHAR 타입 기반, postgre_init.sql 474번 줄 동일)
CREATE INDEX idx_sim_ingredient_price
    ON today_fridge.shopping_item_mcp(ingredient_master_id, unit_price_per_100 ASC)
    WHERE stock_status = 'IN_STOCK';

COMMIT;


-- ===================================================================================
-- [Fix 2] recipe_embedding 테이블 생성
--
-- 원인: pgvector 미설치로 인해 서버 기동 시 Hibernate ddl-auto: update 가
--       테이블 생성을 시도했으나 "vector" 자료형 없음 오류로 실패
-- 엔티티: com.today.fridge.embedding.entity.RecipeEmbedding
-- ===================================================================================

CREATE TABLE IF NOT EXISTS today_fridge.recipe_embedding (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipe_id      BIGINT        NOT NULL,
    embedding_text TEXT          NOT NULL,
    embedding      vector(384)   NOT NULL,
    model_name     VARCHAR(100)  NOT NULL,
    is_active      BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP(6)  NOT NULL,
    CONSTRAINT uk_recipe_embedding_recipe_model UNIQUE (recipe_id, model_name)
);

ALTER TABLE today_fridge.recipe_embedding OWNER TO postgres;

-- FK: recipe_embedding.recipe_id → recipes.recipe_id
ALTER TABLE today_fridge.recipe_embedding
    ADD CONSTRAINT fk_recipe_embedding_recipe
    FOREIGN KEY (recipe_id)
    REFERENCES today_fridge.recipes(recipe_id)
    ON DELETE CASCADE;

-- 조회용 인덱스
CREATE INDEX idx_recipe_embedding_recipe_id
    ON today_fridge.recipe_embedding(recipe_id);

CREATE INDEX idx_recipe_embedding_active
    ON today_fridge.recipe_embedding(is_active);


-- ===================================================================================
-- [Check] postgre_init2.sql 인덱스 적용 여부
--
-- postgre_init2.sql 에 명시된 인덱스 두 가지:
--   1. idx_sim_ingredient_price  → postgre_init.sql 474번 줄에 이미 존재 (위 Fix 1 에서 재생성)
--   2. idx_sim_expires           → postgre_init.sql 475번 줄에 이미 존재
--
-- 결론: 두 인덱스 모두 이미 적용됨. 추가 작업 없음.
-- ===================================================================================
