app:
  naver:
    shopping:
      client-id: ${NAVER_CLIENT_ID:N9SUyMRGr8Dt6N1zgCVl}
      client-secret: ${NAVER_CLIENT_SECRET:1gqwYIfDIH}
  elevenst:
    openapi:
      key: ${ELEVENST_API_KEY:bbc4b7aeadd92902ac44aa5e932d39af}
