naver:
  shopping:
    client-id: ${NAVER_CLIENT_ID:N9SUyMRGr8Dt6N1zgCVl}
    client-secret: ${NAVER_CLIENT_SECRET:1gqwYIfDIH}

coupang:
  partners:
    access-key: ${COUPANG_ACCESS_KEY:}
    secret-key: ${COUPANG_SECRET_KEY:}
